site_name: Code Metrics

theme:
  name: 'material'
  logo: img/codemetrics_logo_plain_transparent.png
  favicon: img/favicon.png
  palette:
    primary: black

plugins:
  - search
  - mermaid2

markdown_extensions:
  - attr_list

nav:
  - Introduction: 'README.md'
  - Getting started: 'getting_started.md'
  - Configuration guide: 'configuration.md'
  - Workloads: 'workloads.md'
  - Feature support: 'features.md'

  - Query types:
    - Bug culprits: 'query_bug_culprits.md'
    - Bugs: 'query_bugs.md'
    - Pipelines: 'query_pipelines.md'
    - Repository churn: 'query_repo_churn.md'
    - Source code metrics: 'query_source_code.md'
    - Vulnerabilities: 'query_vulnerabilities.md'
    - Custom queries: 'custom_queries.md'

  - Configuration:
    - Overview: 'configuration.md'
    - Datastores: 'datastores.md'
    - Secrets management: 'secret_management.md'

    - Authentication:
      - Overview: 'authentication.md'
      - Azure Authentication: 'authentication_azure.md'
      - Cognito Authentication: 'authentication_cognito.md'
      - File Authentication: 'authentication_file.md'
      - Keycloak Authentication: 'authentication_keycloak.md'
      - LDAP Authentication: 'authentication_ldap.md'
      - OpenID Connect (OIDC) Authentication: 'authentication_oidc.md'

    - Configuration files:
      - Code analysis: 'config_code_quality.md'
      - Code management: 'config_code_management.md'
      - Pipelines: 'config_pipelines.md'
      - Project management: 'config_project_management.md'
      - Workloads: 'config_workloads.md'
      - Environment variables: 'env_vars.md'

  - Architecture: 'architecture.md'

  - Other:
    - Prediction: 'prediction.md'
    - Vulnerability report upload: 'vulnerability_report_upload.md'
