name: site
on:
  push:
    branches:
      - main
      - develop
permissions:
  id-token: write
  pages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.x

      - name: Install mkdocs
        run: pip install \
               mkdocs-material \
               mkdocs-mermaid2-plugin

      - name: Build static site
        working-directory: src
        run: mkdocs build --site-dir ../dist

      - name: Upload site
        if: ${{ github.ref_name == 'main' }}
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

      - name: Deploy site
        if: ${{ github.ref_name == 'main' }}
        uses: actions/deploy-pages@v3
